{% set name = "alchemlyb" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/alchemlyb-{{ version }}.tar.gz
  sha256: 3eb0a5e775d25e8e15c8c32c40e90c9b991b64ec2a7d3fdd47c12010a637ef50

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - matplotlib-base
    - numpy
    - pandas >=1.4
    - pymbar >=4
    - python >=3.8
    - scikit-learn
    - scipy

test:
  imports:
    - alchemlyb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alchemistry/alchemlyb
  summary: the simple alchemistry library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - orbeckst
    - jan-janssen
