{% set name = "alchemlyb" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/alchemlyb-{{ version }}.tar.gz
  sha256: 1a18959223d31302a1a3da214b38dd3a7608204f43bb3721fdc6db870dc8139f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - matplotlib-base
    - numpy
    - pandas >=1.4
    - pymbar >=3.0.5,<4
    - python >=3.8
    - scikit-learn
    - scipy

test:
  imports:
    - alchemlyb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alchemistry/alchemlyb
  summary: the simple alchemistry library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - orbeckst
    - jan-janssen
